#!/usr/bin/env node
/**
 * Pre-renders the corridor basemap: public/corridor-map.webp (+ a half-size copy for phones) and the view
 * constants in lib/map-view.ts, which the client uses to project places onto the image (web/docs/21-places-map.md).
 *
 * Why a pre-rendered image and not a tile server: the site is built to be forwarded at scale, and every public
 * tile service (OSM's own, MapTiler, Mapbox) either forbids that traffic or bills for it — a spike would break
 * the map exactly when the site is working. One static image has no key, no quota and no third party in the
 * request path, and it is ~200 KB on a phone.
 *
 * Tiles are fetched ONCE from OpenStreetMap with an identifying User-Agent, then desaturated to sit under the
 * design's ink/amber pins. "© OpenStreetMap contributors" must stay visible on any page that shows the image.
 * Run with `npm run map` after changing the bbox or the gazetteer's extent.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const here = dirname(fileURLToPath(import.meta.url));

// The corridor with a margin: Gyirong (28.40 N, the source region) down to Chitwan (27.55 N), Gorkha to
// Sindhupalchok in longitude. Places outside this box (Kathmandu hospitals, Pokhara) are listed, not plotted.
const BBOX = { north: 28.45, south: 27.55, west: 84.3, east: 85.65 };
const ZOOM = 11;
const TILE = 256;
const TILE_URL = (z, x, y) => `https://tile.openstreetmap.org/${z}/${x}/${y}.png`;
const UA = "nepalfloodtracker-map/1.0 (+https://nepalfloodtracker.com; nepalfloodrescuers@gmail.com)";

const lonToTile = (lon, z) => ((lon + 180) / 360) * 2 ** z;
const latToTile = (lat, z) => {
  const r = (lat * Math.PI) / 180;
  return ((1 - Math.log(Math.tan(r) + 1 / Math.cos(r)) / Math.PI) / 2) * 2 ** z;
};

const x0 = Math.floor(lonToTile(BBOX.west, ZOOM));
const x1 = Math.floor(lonToTile(BBOX.east, ZOOM));
const y0 = Math.floor(latToTile(BBOX.north, ZOOM));
const y1 = Math.floor(latToTile(BBOX.south, ZOOM));
const tilesX = x1 - x0 + 1;
const tilesY = y1 - y0 + 1;
const width = tilesX * TILE;
const height = tilesY * TILE;
console.log(`z${ZOOM} tiles x ${x0}..${x1} (${tilesX})  y ${y0}..${y1} (${tilesY})  → ${width}×${height}`);

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
async function tile(x, y) {
  for (let attempt = 0; attempt < 3; attempt++) {
    const res = await fetch(TILE_URL(ZOOM, x, y), { headers: { "User-Agent": UA, Accept: "image/png" } });
    if (res.ok) return Buffer.from(await res.arrayBuffer());
    if (res.status === 429 || res.status >= 500) await sleep(1500 * (attempt + 1));
    else throw new Error(`tile ${ZOOM}/${x}/${y}: HTTP ${res.status}`);
  }
  throw new Error(`tile ${ZOOM}/${x}/${y}: gave up`);
}

const composites = [];
for (let ty = y0; ty <= y1; ty++) {
  for (let tx = x0; tx <= x1; tx++) {
    composites.push({ input: await tile(tx, ty), left: (tx - x0) * TILE, top: (ty - y0) * TILE });
    process.stdout.write(".");
    await sleep(120); // be a good citizen on the shared tile servers
  }
}
process.stdout.write("\n");

const base = sharp({ create: { width, height, channels: 3, background: "#eceae4" } })
  .composite(composites)
  // desaturate and lift so the amber/green/ink pins read on top; roads and rivers stay legible
  .modulate({ saturation: 0.3, brightness: 1.05 })
  .linear(0.88, 20);

const out = resolve(here, "../public/corridor-map.webp");
const outSm = resolve(here, "../public/corridor-map-sm.webp");
await mkdir(dirname(out), { recursive: true });
const full = await base.clone().webp({ quality: 82 }).toBuffer();
await writeFile(out, full);
const sm = await base.clone().resize(Math.round(width / 2)).webp({ quality: 78 }).toBuffer();
await writeFile(outSm, sm);
console.log(`corridor-map.webp ${(full.length / 1024).toFixed(0)} KB · corridor-map-sm.webp ${(sm.length / 1024).toFixed(0)} KB`);

await writeFile(
  resolve(here, "../lib/map-view.ts"),
  `// Generated by scripts/make-map.mjs — do not edit by hand (npm run map).
// The window public/corridor-map.webp covers, in slippy-map tile coordinates.
import type { MapView } from "./map-projection";

export const CORRIDOR_VIEW: MapView = {
  zoom: ${ZOOM},
  tileX0: ${x0},
  tileY0: ${y0},
  tilesX: ${tilesX},
  tilesY: ${tilesY},
  width: ${width},
  height: ${height},
};

/** The bbox the image was cut to (degrees) — for tests and for deciding which places are plottable. */
export const CORRIDOR_BBOX = { north: ${BBOX.north}, south: ${BBOX.south}, west: ${BBOX.west}, east: ${BBOX.east} };
`,
);
console.log("wrote lib/map-view.ts");
