-- 010 · place_timeline keyed by kind, not by text (docs/data-model.md, pipeline/docs/process_data/03-ledger.md)
--
-- The ledger (process_data step ③) writes one "Status, day by day" line per place × day × kind. The original
-- primary key (place_id, day, what_en) made every changed value a new row: a gauge read at 04:10, 04:20 and 04:30
-- produced three "River gauge live (2.55 m / 2.57 m / 2.59 m)" rows for the same day. `kind` is the template key
-- ("gauge_alive", "opmcm_lost", "reports" …) or "article:<md5 of the headline>" for headline rows, so a re-run
-- replaces the line instead of adding one.

alter table public.place_timeline add column if not exists kind text;

-- backfill: headline rows keep a stable per-title kind (the ledger derives the same value), templated rows are
-- deleted below and regenerated by the next run
update public.place_timeline set kind = 'article:' || md5(what_en) where kind is null;

alter table public.place_timeline alter column kind set not null;
alter table public.place_timeline drop constraint if exists place_timeline_pkey;
alter table public.place_timeline add primary key (place_id, day, kind);

-- one-off: drop the legacy templated rows (they re-appear on the next ledger run with a real kind)
delete from public.place_timeline
where kind like 'article:%'
  and (
       what_en like '% report(s) added on this site'
    or what_en like '% report(s) of people not yet reached'
    or what_en like 'NDRRMA lists % people rescued from here'
    or what_en like 'NDRRMA lists % rescued people held here'
    or what_en like '% people reported missing here on the PM''s portal'
    or what_en like 'River gauge live (% m)'
    or what_en like 'River gauge silent since %'
    or what_en like '% bridge(s) surveyed washed out or damaged'
    or what_en like 'Forecast rain % mm'
    or what_en like 'Morning flying window: %'
    or what_en like 'Mobile network reported %'
    or what_en like '% people registered missing here with NDRRMA (Setu)'
    or what_en like 'District administration lists % people rescued from here'
    or what_en like 'Volunteer rescue bulletin lists % rescued from here'
    or what_en like '% bridge(s) here flagged for inspection (NESRA FloodWatch)'
    or what_en like '% bridge(s) here damaged, % washed out (inventory)'
    or what_en like 'Copernicus EMS: % of % buildings affected'
    or what_en like '% open help request(s) here on the PM''s portal (% critical)'
    or what_en like '% people reported affected here (PM''s portal help requests)'
  );

comment on column public.place_timeline.kind is 'template key of the line (gauge_alive, opmcm_lost, reports …) or article:<md5(title)>; one row per place × day × kind';
