// Generated by scripts/make-map.mjs — do not edit by hand (npm run map).
// The window public/corridor-map.webp covers, in slippy-map tile coordinates.
import type { MapView } from "./map-projection";

export const CORRIDOR_VIEW: MapView = {
  zoom: 12,
  tileX0: 3008,
  tileY0: 1710,
  tilesX: 15,
  tilesY: 12,
  width: 3840,
  height: 3072,
};

/** The bbox the image was cut to (degrees) — for tests and for deciding which places are plottable. */
export const CORRIDOR_BBOX = { north: 28.44, south: 27.58, west: 84.38, east: 85.62 };
