// Generated by scripts/make-map.mjs — do not edit by hand (npm run map).
// The window public/corridor-map.webp covers, in slippy-map tile coordinates.
import type { MapView } from "./map-projection";

export const CORRIDOR_VIEW: MapView = {
  zoom: 11,
  tileX0: 1503,
  tileY0: 855,
  tilesX: 9,
  tilesY: 6,
  width: 2304,
  height: 1536,
};

/** The bbox the image was cut to (degrees) — for tests and for deciding which places are plottable. */
export const CORRIDOR_BBOX = { north: 28.45, south: 27.55, west: 84.3, east: 85.65 };
