-- The first hours of 26 Aug 2026, reconstructed from the DHM Flood Forecasting Division technical report
-- (via Kathmandu Post 10-hour timeline 27 Aug, OnlineKhabar), USGS ComCat, NDRRMA sitreps, ICIMOD.
-- Times are NPT (UTC+5:45). Sources: aryaa_research_general/agent-reports/deepdive-signals-2026-08-29.md §4.3,
-- research/00-event/timeline.md. Re-runnable (upsert).
insert into event_timeline (id, at, at_label, place_id, km, what_en, what_ne, what_hi, kind, source, source_url) values
('t0820_tremor',      '2026-08-26 02:35+00', '08:20', 'rasuwagadhi', 0,  'A small tremor (~M2.6) is felt near Rasuwagadhi.', 'रसुवागढी नजिक सानो कम्पन (~M2.6) महसुस।', 'रसुवागढ़ी के पास हल्का झटका (~M2.6) महसूस हुआ।', 'trigger', 'DHM technical report', 'https://kathmandupost.com/national/2026/08/28/what-triggered-the-rasuwa-flood-scientists-piece-together-a-complex-chain-of-events'),
('t0837_collapse',    '2026-08-26 02:52+00', '08:37', 'barrier_lake_site', -8, 'A ~600 m section of glacier and rock falls ~1,200 m into the Lhende Khola. Seismometers record it as a magnitude-5.2 event (USGS us7000tbwb).', 'करिब ६०० मि. चौडा हिमनदी र चट्टान ~१,२०० मि. तल लेन्दे खोलामा खस्यो; भूकम्पमापीले ५.२ म्याग्निच्युड दर्ता गर्‍यो।', 'लगभग 600 मीटर चौड़ा ग्लेशियर और चट्टान का हिस्सा ~1,200 मीटर नीचे लेंदे खोला में गिरा; भूकंपमापी ने इसे 5.2 तीव्रता की घटना दर्ज किया।', 'trigger', 'USGS', 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000tbwb'),
('t0840_gyirong',     '2026-08-26 02:55+00', '08:40', 'gyirong_port', -3, 'The surge reaches Gyirong (Kerung) Port about seven minutes after the collapse — roughly 190 km/h over the first 22 km.', 'पहिरो सुरु भएको करिब ७ मिनेटमा बाढी केरुङ नाकामा पुग्यो — पहिलो २२ किमिमा करिब १९० किमि/घण्टा।', 'ढहने के लगभग सात मिनट बाद बाढ़ केरुंग बंदरगाह तक पहुँची — पहले 22 किमी में करीब 190 किमी/घंटा।', 'wave', 'ICIMOD / Kathmandu Post', 'https://www.icimod.org/press-release/major-flash-flood-sweeps-through-nepals-rasuwa-district-raising-fears-of-further-downstream-flooding/'),
('t0840_rasuwagadhi', '2026-08-26 02:55+00', '08:40', 'rasuwagadhi', 0,  'Last reading from the Rasuwagadhi river gauge (1.62 m) before it is destroyed. The border post, customs yard and the Miteri bridge are swept away.', 'रसुवागढी जलमापन केन्द्रको अन्तिम रिडिङ (१.६२ मि.); त्यसपछि केन्द्र नष्ट। नाका, भन्सार र मितेरी पुल बगायो।', 'रसुवागढ़ी नदी गेज की अंतिम रीडिंग (1.62 मी.) और फिर गेज नष्ट। सीमा चौकी, कस्टम यार्ड और मितेरी पुल बह गए।', 'gauge', 'DHM river watch', 'https://dhm.gov.np/hydrology/river-watch'),
('t0845_timure',      '2026-08-26 03:00+00', '08:45', 'timure', 4,   'Timure: the last completed phone calls out. Survivors run uphill into the forest within seconds.', 'टिमुरे: अन्तिम फोन सम्पर्क। बाँचेकाहरू केही सेकेन्डमै जंगलतिर माथि भागे।', 'तिमुरे: आखिरी फोन कॉल। बचे लोग कुछ ही सेकंड में जंगल की ओर ऊपर भागे।', 'impact', 'Kathmandu Post survivor accounts', 'https://kathmandupost.com/national/2026/08/28/they-watched-settlements-disappear-beneath-a-wall-of-water-and-mud-somehow-they-survived'),
('t0850_syabrubesi',  '2026-08-26 03:05+00', '08:50', 'syabrubesi', 16, 'Syabrubesi gauges go offline (Bhote Koshi 3.80 m, Langtang Khola 2.81 m). The bazaar, lodges and helipad are hit.', 'स्याफ्रुबेसीका जलमापन केन्द्र बन्द (भोटेकोशी ३.८० मि., लाङटाङ खोला २.८१ मि.)। बजार, लज र हेलिप्याड प्रभावित।', 'स्याफ्रुबेसी गेज ऑफलाइन (भोटेकोशी 3.80 मी., लांगटांग खोला 2.81 मी.)। बाज़ार, लॉज और हेलीपैड प्रभावित।', 'gauge', 'DHM river watch', 'https://dhm.gov.np/hydrology/river-watch'),
('t0900_alert',       '2026-08-26 03:15+00', '09:00', 'betrawati', 40, 'Rasuwa DAO and the Betrawati gauge-keeper phone the Flood Forecasting Division; the warning chain starts by telephone.', 'रसुवा प्रजिका र बेत्रावती गेजकिपरले बाढी पूर्वानुमान महाशाखालाई फोन; चेतावनी टेलिफोनबाट सुरु।', 'रसुवा DAO और बेत्रावती गेज-कीपर ने बाढ़ पूर्वानुमान विभाग को फोन किया; चेतावनी श्रृंखला फोन से शुरू।', 'warning', 'DHM technical report', 'https://english.onlinekhabar.com/'),
('t0915_sms',         '2026-08-26 03:30+00', '09:15', null, null, 'DHM sends a warning SMS to 679,295 subscribers in Rasuwa, Nuwakot, Dhading and Chitwan. Workers at Upper Trishuli-1 report an alert ~30 s before the wave.', 'जल तथा मौसम विज्ञान विभागले रसुवा, नुवाकोट, धादिङ र चितवनका ६,७९,२९५ ग्राहकलाई चेतावनी एसएमएस पठायो।', 'DHM ने रसुवा, नुवाकोट, धादिंग और चितवन के 6,79,295 ग्राहकों को चेतावनी SMS भेजा।', 'warning', 'DHM technical report', 'https://english.onlinekhabar.com/'),
('t0920_betrawati',   '2026-08-26 03:35+00', '09:20', 'betrawati', 40, 'Betrawati: last gauge reading (3.55 m); the bridge that links Rasuwa to Nuwakot is gone minutes later.', 'बेत्रावती: अन्तिम गेज रिडिङ (३.५५ मि.); रसुवालाई नुवाकोटसँग जोड्ने पुल केही मिनेटमै बग्यो।', 'बेत्रावती: अंतिम गेज रीडिंग (3.55 मी.); रसुवा को नुवाकोट से जोड़ने वाला पुल कुछ मिनट बाद बह गया।', 'gauge', 'DHM river watch', 'https://dhm.gov.np/hydrology/river-watch'),
('t1028_galchhi',     '2026-08-26 04:43+00', '10:28', 'galchhi', 60, 'Galchhi alert: the Trishuli rises ~9 m in 30 minutes, 60 km downstream. Prithvi Highway and Mugling–Narayanghat put on high alert.', 'गल्छी चेतावनी: ६० किमि तल त्रिशूली ३० मिनेटमा ~९ मि. बढ्यो। पृथ्वी राजमार्ग र मुग्लिन–नारायणघाट उच्च सतर्कता।', 'गल्छी अलर्ट: 60 किमी नीचे त्रिशूली 30 मिनट में ~9 मी. चढ़ी। पृथ्वी राजमार्ग और मुग्लिंग–नारायणघाट हाई अलर्ट पर।', 'gauge', 'ICIMOD / DHM', 'https://www.icimod.org/press-release/major-flash-flood-sweeps-through-nepals-rasuwa-district-raising-fears-of-further-downstream-flooding/'),
('t1126_malekhu',     '2026-08-26 05:41+00', '11:26', 'malekhu', 68, 'Malekhu (Furke Khola) crosses the warning level; at 11:40 it reads 10.48 m — above danger — and the gauge dies. The bridge is destroyed at 11:43.', 'मलेखु (फुर्के खोला) चेतावनी तह नाघ्यो; ११:४० मा १०.४८ मि. — खतराभन्दा माथि — र गेज बन्द। ११:४३ मा पुल ध्वस्त।', 'मलेखु (फुर्के खोला) चेतावनी स्तर पार; 11:40 पर 10.48 मी. — खतरे से ऊपर — और गेज बंद। 11:43 पर पुल ध्वस्त।', 'gauge', 'BIPAD river stations', 'https://bipadportal.gov.np/'),
('t1300_devghat',     '2026-08-26 07:15+00', '13:00', 'devghat', 100, 'The flood passes Mugling; Devghat is evacuated. Devghat reads 4.76 m at 13:30.', 'बाढी मुग्लिन पार; देवघाट खाली गराइयो। १३:३० मा देवघाट ४.७६ मि.।', 'बाढ़ मुग्लिंग पार; देवघाट खाली कराया गया। 13:30 पर देवघाट 4.76 मी.।', 'warning', 'DHM technical report', 'https://english.onlinekhabar.com/'),
('t1414_kalikhola',   '2026-08-26 08:29+00', '14:14', null, 72, 'Trishuli at Kali Khola peaks at 12.3 m (danger level 12.1 m).', 'कालीखोलामा त्रिशूली १२.३ मि. मा उच्चतम (खतरा तह १२.१ मि.)।', 'काली खोला में त्रिशूली 12.3 मी. पर चरम (खतरा स्तर 12.1 मी.)।', 'gauge', 'DHM river watch', 'https://dhm.gov.np/hydrology/river-watch'),
('t1600_devghat_peak','2026-08-26 10:15+00', '16:00', 'devghat', 100, 'Narayani at Devghat peaks at 6.57 m (~5,850 m³/s). Bodies will later be recovered up to ~240 km downstream, into Uttar Pradesh.', 'देवघाटमा नारायणी ६.५७ मि. मा उच्चतम (~५,८५० घन मि./से.)। पछि ~२४० किमि तलसम्म शव फेला।', 'देवघाट में नारायणी 6.57 मी. पर चरम (~5,850 घन मी./से.)। बाद में ~240 किमी नीचे उत्तर प्रदेश तक शव मिले।', 'gauge', 'DHM river watch', 'https://dhm.gov.np/hydrology/river-watch'),
('t1145_second',      '2026-08-26 06:00+00', '11:45', 'barrier_lake_site', -8, 'A second mass movement (magnitude 4.2, USGS us7000tc90) at the same site — the window in which the first barrier lake is thought to have breached.', 'उही स्थानमा दोस्रो पहिरो (४.२ म्याग्निच्युड) — पहिलो थुनिएको ताल फुटेको मानिने समय।', 'उसी स्थान पर दूसरा भूस्खलन (तीव्रता 4.2) — जब पहली बांध-झील टूटी मानी जाती है।', 'trigger', 'USGS', 'https://earthquake.usgs.gov/earthquakes/eventpage/us7000tc90'),
('d2_breach',         '2026-08-28 04:30+00', '28 Aug', 'barrier_lake_site', -8, 'The lower barrier lake overtops; rescue is suspended for ~3 hours and crews pull back 1 km. Downstream rise ~0.6 m.', 'तल्लो थुनिएको ताल पोखियो; उद्धार ~३ घण्टा रोकियो, टोली १ किमि पछि। तल ~०.६ मि. वृद्धि।', 'निचली बांध-झील उफनी; बचाव ~3 घंटे रुका, दल 1 किमी पीछे। नीचे ~0.6 मी. वृद्धि।', 'warning', 'Kathmandu Post', 'https://kathmandupost.com/'),
('d3_ut1_rescue',     '2026-08-28 10:00+00', '28 Aug', 'ut1_mailung_camp', 26, '350 workers are brought out alive from the Upper Trishuli hydropower tunnel; 100+ remain inside. 7 military and 7 civilian helicopters fly 200+ sorties.', 'माथिल्लो त्रिशूली सुरुङबाट ३५० जना जीवित निकालियो; १००+ भित्रै। ७ सैनिक र ७ निजी हेलिकप्टरका २००+ उडान।', 'ऊपरी त्रिशूली सुरंग से 350 लोग जीवित निकाले गए; 100+ अंदर। 7 सैन्य और 7 निजी हेलीकॉप्टरों की 200+ उड़ानें।', 'response', 'Kathmandu Post', 'https://kathmandupost.com/national/2026/08/29/hundreds-feared-trapped-in-hydropower-tunnels-after-bhotekoshi-flood')
on conflict (id) do update set at = excluded.at, at_label = excluded.at_label, place_id = excluded.place_id, km = excluded.km,
  what_en = excluded.what_en, what_ne = excluded.what_ne, what_hi = excluded.what_hi, kind = excluded.kind, source = excluded.source, source_url = excluded.source_url;
