#!/usr/bin/env python3
"""Generate seed/sources.sql from ../sources.yaml (docs/07-applying-migrations.md, step 4)."""
from __future__ import annotations
import re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "sources.yaml"
OUT = Path(__file__).resolve().parent / "sources.sql"

GROUP_BY_PREFIX = [
    ("opmcm", "government"), ("ndrrma", "government"), ("setu", "government"), ("police", "government"),
    ("mofa", "government"), ("heoc", "government"), ("dao_", "government"), ("bipad", "government"),
    ("dhm", "government"), ("dor_", "government"), ("china", "government"), ("us_embassy", "government"),
    ("reliefweb", "humanitarian"), ("ifrc", "humanitarian"), ("gdacs", "humanitarian"),
    ("hot_", "geospatial"), ("hdx", "geospatial"), ("emsr", "geospatial"), ("nesra", "geospatial"),
    ("microsoft", "geospatial"), ("vantor", "geospatial"), ("planet", "geospatial"), ("oam", "geospatial"),
    ("cdse", "geospatial"), ("hf_", "geospatial"), ("usgs", "signals"), ("geofon", "signals"),
    ("openmeteo", "signals"), ("ntc", "signals"), ("outlet", "news"), ("google_news", "news"),
    ("ekantipur", "news"), ("live_blogs", "news"), ("china_search", "news"), ("wikipedia", "news"),
    ("gdelt", "news"), ("volunteer", "community"),
]

RELIABILITY = {  # A official/machine-readable · B official or wire, hand-checked · C credible/unverified · D raw/duplicated
    "government": "A", "humanitarian": "A", "geospatial": "B", "signals": "A", "news": "C", "community": "D",
}
OVERRIDES = {"opmcm_person_reports": "D", "volunteer_bulletin_repo": "C", "setu_recordlist": "B",
             "outlet_rss_set": "B", "live_blogs": "B", "wikipedia_revisions": "C", "gdelt_monitor": "D",
             "ntc_restoration_articles": "B", "openmeteo_corridor": "B", "china_search_apis": "C"}

def reliability_for(sid: str, grp: str) -> str:
    return OVERRIDES.get(sid, RELIABILITY[grp])

def group_for(sid: str) -> str:
    for pre, g in GROUP_BY_PREFIX:
        if sid.startswith(pre):
            return g
    return "community"

def q(v) -> str:
    if v is None: return "null"
    if isinstance(v, bool): return "true" if v else "false"
    return "$$" + str(v).replace("$$", "$ $") + "$$"

def main() -> int:
    try:
        import yaml  # type: ignore
        data = yaml.safe_load(SRC.read_text())["sources"]
    except ImportError:
        sys.exit("pip install pyyaml")
    rows = []
    for s in data:
        url = s.get("url")
        if isinstance(url, list): url = url[0]
        name = s["id"].replace("_", " ").title()
        pii = s.get("pii")
        pii_bool = True if pii in (True, "mixed", "true") else False
        rows.append(
            f"({q(s['id'])}, {q(name)}, {q(group_for(s['id']))}, {q(s.get('family'))}, {q(url)}, "
            f"{q(s.get('reliability') or reliability_for(s['id'], group_for(s['id'])))}, {q(pii_bool)}, "
            f"{q(s.get('cadence'))}, {q(s.get('holds'))}, {q(s.get('catalogue'))})"
        )
    sql = (
        "-- GENERATED by seed/gen_sources.py from sources.yaml — do not edit by hand.\n"
        "insert into sources (id, name, grp, family, url, reliability, pii, cadence, holds, catalogue) values\n"
        + ",\n".join(rows)
        + "\non conflict (id) do update set name = excluded.name, grp = excluded.grp, family = excluded.family, "
          "url = excluded.url, reliability = excluded.reliability, pii = excluded.pii, cadence = excluded.cadence, "
          "holds = excluded.holds, catalogue = excluded.catalogue;\n"
    )
    OUT.write_text(sql)
    print(f"wrote {OUT} ({len(rows)} sources)")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
