#!/usr/bin/env python3
"""
to_sql.py — places.csv → ../db/seed/places.sql (see README.md, step 3).

    places.csv ──▶ one `insert into places (...) values (...), (...) on conflict (id) do update set ...`

Text is dollar-quoted with the tag $p$ (so apostrophes, quotes and Devanagari need no escaping);
aliases become a text[] via array[$p$…$p$, …]::text[]; blanks become null; booleans are bare.
The file is one statement so db/apply.py can run it as a single query.

    python to_sql.py                 # writes ../db/seed/places.sql
    python to_sql.py --out x.sql     # elsewhere
"""
from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
CSV_PATH = HERE / "places.csv"
SQL_PATH = HERE.parent / "db" / "seed" / "places.sql"

COLUMNS = [
    "id", "name_en", "name_ne", "name_hi", "name_zh", "aliases", "kind", "district",
    "municipality", "ward", "lat", "lon", "elev_m", "km", "side", "in_channel",
    "below_barrier_lakes", "notes",
]
TEXT = {"id", "name_en", "name_ne", "name_hi", "name_zh", "kind", "district", "municipality", "side", "notes"}
INT = {"ward", "elev_m"}
FLOAT = {"lat", "lon", "km"}
BOOL = {"in_channel", "below_barrier_lakes"}
TAG = "$p$"


def q(text: str) -> str:
    if TAG in text:
        raise ValueError(f"value contains the dollar-quote tag {TAG}: {text!r}")
    return f"{TAG}{text}{TAG}"


def sql_value(col: str, raw: str) -> str:
    v = (raw or "").strip()
    if col == "aliases":
        parts = [p.strip() for p in v.split("|") if p.strip()]
        return "array[" + ", ".join(q(p) for p in parts) + "]::text[]" if parts else "'{}'::text[]"
    if col in BOOL:
        if v.lower() not in ("true", "false"):
            raise ValueError(f"{col}: expected true/false, got {raw!r}")
        return v.lower()
    if v == "":
        return "null"
    if col in INT:
        return str(int(v))
    if col in FLOAT:
        return repr(float(v))
    if col in TEXT:
        return q(v)
    raise ValueError(f"unknown column {col}")


def rows_from_csv(path: Path = CSV_PATH) -> list[dict]:
    with path.open(encoding="utf-8", newline="") as fh:
        r = csv.DictReader(fh)
        if r.fieldnames != COLUMNS:
            raise SystemExit(f"{path}: header mismatch\n  got  {r.fieldnames}\n  want {COLUMNS}")
        return list(r)


def render(rows: list[dict]) -> str:
    lines = [
        "-- GENERATED by gazetteer/to_sql.py from gazetteer/places.csv — do not edit by hand.",
        f"-- {len(rows)} places. Re-generate: python gazetteer/to_sql.py",
        f"insert into places ({', '.join(COLUMNS)}) values",
    ]
    body = []
    for row in rows:
        body.append("(" + ", ".join(sql_value(c, row.get(c, "")) for c in COLUMNS) + ")")
    lines.append(",\n".join(body))
    updates = ", ".join(f"{c} = excluded.{c}" for c in COLUMNS if c != "id")
    lines.append(f"on conflict (id) do update set {updates};")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--csv", type=Path, default=CSV_PATH)
    ap.add_argument("--out", type=Path, default=SQL_PATH)
    a = ap.parse_args(argv)
    rows = rows_from_csv(a.csv)
    a.out.parent.mkdir(parents=True, exist_ok=True)
    a.out.write_text(render(rows), encoding="utf-8")
    print(f"wrote {a.out} — {len(rows)} rows")
    return 0


if __name__ == "__main__":
    sys.exit(main())
